"""empty message

Revision ID: 680ed2a6e398
Revises: 53dcd9c72717
Create Date: 2018-03-17 10:19:47.677208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680ed2a6e398'
down_revision = '53dcd9c72717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_item', sa.Column('status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list_item', 'status')
    # ### end Alembic commands ###
